version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:latest
    steps:
      - run:
          name: Install dependencies of CI script
          command: nix-env -Q -i git rsync
      - run:
          name: Make SSL certificates available to artifact uploader
          command: |
            src=$(nix-build '<nixpkgs>' -A cacert --no-out-link)/etc/ssl/certs
            dest=/etc/ssl/certs
            mkdir -p $dest
            cp -R $src/* $dest
      - checkout:
          name: Checkout project source
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: Compile project
          command: nix-build --arg withUploadSupport false
      - run:
          name: Rearrange build artifacts
          command: |
            mkdir -p /artifacts
            cp result/* /artifacts
      - store_artifacts:
          name: Store build artifacts
          path: /artifacts
