version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:latest
    steps:
      - run:
          name: Install dependencies of CI script
          command: |
            nixflags="--no-build-output --no-out-link --show-trace --timeout 300"

            # Install git into a place where circleci's "checkout" step can find
            # it.
            git_pkg=$(nix-build $nixflags '<nixpkgs>' -A git)
            src=$git_pkg/bin/git
            dest=/usr/bin/git
            mkdir -p $(dirname $dest)
            ln -s $src $dest

            # Install SSL certificates into a place where circleci's
            # "store_artifacts" step can find them.
            cacert_pkg=$(nix-build $nixflags '<nixpkgs>' -A cacert)
            src=$cacert_pkg/etc/ssl/certs
            dest=/etc/ssl/certs
            mkdir -p $(dirname $dest)
            ln -s $src $dest
      - checkout:
          name: Checkout project source
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: Compile project
          command: nix-build
      - run:
          name: Rearrange build artifacts
          command: |
            mkdir -p /artifacts
            cp result/* /artifacts
      - store_artifacts:
          name: Store build artifacts
          path: /artifacts
